version: '2'
services:
  normas-app:
    image: normas
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://normas-mariadb:3306/normas?useLegacyDatetimeCode=false&serverTimezone=UTC
      - JHIPSTER_SLEEP=30 # gives time for mariadb server to start
    ports:
      - 8082:8082
    depends_on:
      - normas-mariadb
    restart: always
  normas-mariadb:
    image: mariadb:10.4.10
    volumes:
      - ../volumes/normas-mariadb:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=normas
    ports:
      - 3308:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    restart: always

  consultoria-app:
    image: consultoria
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://consultoria-mariadb:3306/consultoria?useLegacyDatetimeCode=false&serverTimezone=UTC
      - JHIPSTER_SLEEP=30 # gives time for mariadb server to start
    ports:
      - 8083:8083
    depends_on:
      - consultoria-mariadb
    restart: always
  consultoria-mariadb:
    image: mariadb:10.4.10
    volumes:
      - ../volumes/consultoria-mariadb:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=consultoria
    ports:
      - 3309:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    restart: always

