version: '2'
services:
  normas-app:
    image: normas
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://normas-mariadb:3306/normas
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
  normas-mariadb:
    image: mariadb:10.4.10
    volumes:
      - vol-normas-mariadb:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=normas
    ports:
      - 3308:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp

  consultoria-app:
    image: consultoria
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://consultoria-mariadb:3306/consultoria
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
  consultoria-mariadb:
    image: mariadb:10.4.10
    volumes:
      - vol-consultoria-mariadb:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=consultoria
    ports:
      - 3309:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp

  #mock-prometheus:
    #extends:
      #file: monitoring.yml
      #service: mock-prometheus
  #mock-grafana:
    #extends:
      #file: monitoring.yml
      #service: mock-grafana

volumes:
  vol-normas-mariadb:
  vol-consultoria-mariadb: