version: '2'
services:
  normas-app:
    image: normas
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://normas-mariadb:3306/normas
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
  normas-mariadb:
    extends:
      file: mariadb.yml
      service: normas-mariadb
