version: '2'
services:
  consultoria-app:
    image: consultoria
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://consultoria-mariadb:3306/consultoria
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
  consultoria-mariadb:
    extends:
      file: mariadb.yml
      service: consultoria-mariadb
